### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by srstevenson**
I appended `-Ywarn-unused-import` to the `scalac` options in `build.sbt` for this, but haven't included that change in this PR as it doesn't play well with the (convenient) wildcard import in `initialCommands`:

```
$ sbt console
[info] Loading project definition from /home/srs/src/github.com/ASIDataScience/scala-plotly-client/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to plotly (in build file:/home/srs/src/github.com/ASIDataScience/scala-plotly-client/)
[info] Starting scala interpreter...
[info]
<console>:12: warning: Unused import
       import co.theasi.plotly._
                               ^
import co.theasi.plotly._
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_102).
Type in expressions for evaluation. Or try :help.

scala> <console>:10: warning: Unused import
import co.theasi.plotly._
                        ^
scala>
```

### CODE REVIEW

**Comment by pbugnion** [comment]
I'm mildly in favour of adding the compiler flag anyway. I don't think the warning matters too much. An alternative would be to set up a linter. 

Anyway, this PR looks good.

**Comment by srstevenson** [comment]
Sounds good, I've pushed 2114c48e081bda9693f5c1320904da1b97d74fa3 to this branch to add the flag.

**Comment by srstevenson** [comment]
Travis is failing because 2.10.6 doesn't understand `-Ywarn-unused-import`.

**Comment by pbugnion** [comment]
Annoyingly, 2.10.6 is still fairly common and we don't really test against it locally (at least I don't), so it's the perfect use case for Travis.

We can conditionally turn compiler flags on with a snippet like this in build.sbt. It's a bit ugly, but it works:

```
val scalac = "2.11.8" // defines the scala version

scalaVersion := scalac

scalacOptions += { if (scalac == "2.11.8") { "-Ywarn-unused-import" } else "" }
```

There may be a more elegant way to retrieve the version of Scala, but I don't understand sbt well enough.

**Comment by srstevenson** [comment]
I've implemented what I think is a slightly more elegant solution in c6c1e3df85ff6c95eba85499e6966539db521a6f, let me know what you think.

**Comment by pbugnion** [comment]
Ah -- that is much better.

**Comment by pbugnion** [comment]
Go ahead and merge!

**Pull request merged**
