### PR TITLE
Initial implementation of bar charts

### PR DESCRIPTION
**Pull request by nickrobinson251**
Bar charts weren't being serialised correctly. Now fixed.

### CODE REVIEW

**Comment by pbugnion** [comment]
This is great! Let's add Scaladocs and unit tests and this will be ready to merge.

**Comment by alexdeleon** [comment]
It would be nice to merge this PR :)

**Comment by pbugnion** [comment]
Use as follows:

```
scalaVersion := "2.11.11"

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

libraryDependencies ++= Seq(
  "co.theasi" %% "plotly" % "0.2.1-SNAPSHOT"
)
```

```scala
import scala.util.Random

import co.theasi.plotly._

object Main extends App {
  val numberPoints = 30
  val xs: Vector[Double] = Vector.range(0, numberPoints).map { _.toDouble }
  val ys: Vector[Double] = Vector.fill(numberPoints) { Random.nextGaussian() }

  val p = CartesianPlot()
    .withBar(
      xs, ys,
      BarOptions()
        .updatedMarker(
          _.color(0, 170, 255, 0.5)
            .lineColor(0, 170, 255,1.0)
            .lineWidth(1)
        )
    )

  val result = draw(p, "bar-plot-example")

  println(result)
}
```

**Comment by pbugnion** [comment]
Now available in `0.2.1-SNAPSHOT` on sonatype:

```
scalaVersion := "2.11.11"

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

libraryDependencies ++= Seq(
  "co.theasi" %% "plotly" % "0.2.1-SNAPSHOT"
)
```

**Comment by pbugnion** [comment]
Thanks to @nickrobinson251 for doing all the hard work on this.

**Pull request merged**
